language: c

os:
  - linux
  - osx

env:
  - FISH_PPA=nightly-master BREW_OPTIONS=--HEAD

before_install:
  - script/bootstrap.sh

script: script/run-tests.fish

notifications:
  email:
    on_success: never
    on_failure: change
